from django.urls import path

from . import views, views_ops as f, views_setup as e, views_students as d

urlpatterns = [
    # B
    path("school", views.OverviewView.as_view(), name="school-overview"),
    path("school/sales", views.SalesView.as_view(), name="school-sales"),
    path("school/sales/transactions/<int:pk>", views.TransactionDrawerView.as_view(), name="school-transaction"),
    path("school/reconciliation", views.ReconciliationView.as_view(), name="school-reconciliation"),
    path("school/reconciliation/export", views.ReconciliationExportView.as_view(), name="school-reconciliation-csv"),
    path("school/shortfalls", views.ShortfallsView.as_view(), name="school-shortfalls"),
    path("school/shortfalls/<int:pk>/resolve", views.ResolveReviewView.as_view(), name="school-shortfall-resolve"),
    path("school/_picker/students", views.StudentPickerView.as_view(), name="school-student-picker"),
    # C
    path("school/analytics", views.AnalyticsView.as_view(), name="school-analytics"),
    # D
    path("school/students", d.StudentsView.as_view(), name="school-students"),
    path("school/students/new", d.StudentFormView.as_view(), name="school-student-new"),
    path("school/students/<int:pk>", d.StudentDetailView.as_view(), name="school-student"),
    path("school/students/<int:pk>/edit", d.StudentFormView.as_view(), name="school-student-edit"),
    path("school/students/<int:pk>/guardian-lookup", d.GuardianLookupView.as_view(), name="school-guardian-lookup"),
    path("school/students/<int:pk>/link-guardian", d.LinkGuardianView.as_view(), name="school-guardian-link"),
    path("school/students/<int:pk>/portal/create", d.PortalCreateView.as_view(), name="school-portal-create"),
    path("school/students/<int:pk>/portal/remove", d.PortalRemoveView.as_view(), name="school-portal-remove"),
    path("school/guardians", d.GuardiansView.as_view(), name="school-guardians"),
    path("school/guardians/<int:pk>/unlink", d.UnlinkGuardianView.as_view(), name="school-guardian-unlink"),
    path("school/guardians/kyc/<int:pk>/review", d.ReviewKycView.as_view(), name="school-kyc-review"),
    path("school/cards", d.CardsView.as_view(), name="school-cards"),
    path("school/cards/issue", d.IssueCardView.as_view(), name="school-card-issue"),
    path("school/cards/uid-preview", d.CardUidPreviewView.as_view(), name="school-card-uid-preview"),
    path("school/cards/<int:pk>/reissue", d.IssueCardView.as_view(), name="school-card-reissue"),
    path("school/cards/<int:pk>/freeze", d.FreezeCardView.as_view(), name="school-card-freeze"),
    path("school/cards/<int:pk>/unfreeze", d.UnfreezeCardView.as_view(), name="school-card-unfreeze"),
    path("school/cards/<int:pk>/mark-lost", d.MarkLostView.as_view(), name="school-card-lost"),
    path("school/cards/<int:pk>/reset-pin", d.ResetPinView.as_view(), name="school-card-reset-pin"),
    # E
    path("school/devices", e.DevicesView.as_view(), name="school-devices"),
    path("school/devices/register", e.RegisterDeviceView.as_view(), name="school-device-register"),
    path("school/devices/qr", e.DeviceQrView.as_view(), name="school-device-qr"),
    path("school/devices/<int:pk>/rotate-token", e.RotateTokenView.as_view(), name="school-device-rotate"),
    path("school/devices/<int:pk>/revoke", e.RevokeDeviceView.as_view(), name="school-device-revoke"),
    path("school/merchants", e.MerchantsView.as_view(), name="school-merchants"),
    path("school/merchants/new", e.NewMerchantView.as_view(), name="school-merchant-new"),
    path("school/merchants/<int:pk>/approve", e.ApproveMerchantView.as_view(), name="school-merchant-approve"),
    path("school/merchants/<int:pk>/suspend", e.SuspendMerchantView.as_view(), name="school-merchant-suspend"),
    path("school/merchants/<int:pk>/statement", e.MerchantStatementView.as_view(), name="school-merchant-statement"),
    path("school/products", e.ProductsView.as_view(), name="school-products"),
    path("school/products/new", e.ProductFormView.as_view(), name="school-product-new"),
    path("school/products/<int:pk>/edit", e.ProductFormView.as_view(), name="school-product-edit"),
    path("school/products/<int:pk>/delete", e.DeleteProductView.as_view(), name="school-product-delete"),
    path("school/products/categories/new", e.CategoryFormView.as_view(), name="school-category-new"),
    path("school/products/categories/<int:pk>/edit", e.CategoryFormView.as_view(), name="school-category-edit"),
    path("school/products/categories/<int:pk>/delete", e.DeleteCategoryView.as_view(), name="school-category-delete"),
    path("school/policy", e.PolicyView.as_view(), name="school-policy"),
    path("school/policy/default", e.SaveDefaultPolicyView.as_view(), name="school-policy-default"),
    path("school/policy/settings", e.SaveSchoolSettingsView.as_view(), name="school-policy-settings"),
    path("school/policy/overrides/<int:pk>/remove", e.RemoveOverrideView.as_view(), name="school-override-remove"),
    path("school/staff", e.StaffView.as_view(), name="school-staff"),
    path("school/staff/new", e.NewStaffView.as_view(), name="school-staff-new"),
    path("school/staff/<int:pk>/toggle", e.ToggleStaffView.as_view(), name="school-staff-toggle"),
    path("school/staff/<int:pk>/set-password", e.SetStaffPasswordView.as_view(), name="school-staff-password"),
    # F
    path("school/fees", f.FeesView.as_view(), name="school-fees"),
    path("school/fees/payments/export", f.FeePaymentsExportView.as_view(), name="school-fees-csv"),
    path("school/fees/categories/new", f.FeeCategoryFormView.as_view(), name="school-fee-category-new"),
    path("school/fees/categories/<int:pk>/edit", f.FeeCategoryFormView.as_view(), name="school-fee-category-edit"),
    path("school/fees/categories/<int:pk>/pay", f.PayFeeView.as_view(), name="school-fee-pay"),
    path("school/attendance", f.AttendanceView.as_view(), name="school-attendance"),
    path("school/attendance/export", f.AttendanceRegisterExportView.as_view(), name="school-attendance-csv"),
    path("school/attendance/student-export", f.AttendanceStudentExportView.as_view(), name="school-attendance-student-csv"),
    path("school/pooled-funds", f.PooledFundsView.as_view(), name="school-funds"),
    path("school/pooled-funds/new", f.NewFundView.as_view(), name="school-fund-new"),
    path("school/pooled-funds/<int:pk>", f.FundDrawerView.as_view(), name="school-fund"),
    path("school/pooled-funds/<int:pk>/close", f.CloseFundView.as_view(), name="school-fund-close"),
    path("school/pooled-funds/<int:pk>/disburse", f.DisburseView.as_view(), name="school-fund-disburse"),
    path("school/disputes", f.DisputesView.as_view(), name="school-disputes"),
    path("school/disputes/<int:pk>", f.DisputeDrawerView.as_view(), name="school-dispute"),
    path("school/disputes/<int:pk>/review", f.StartReviewView.as_view(), name="school-dispute-review"),
    path("school/disputes/<int:pk>/resolve", f.ResolveDisputeView.as_view(), name="school-dispute-resolve"),
    path("school/p2p-alerts", f.P2PAlertsView.as_view(), name="school-p2p-alerts"),
    path("school/p2p-alerts/<int:pk>/history", f.P2PHistoryDrawerView.as_view(), name="school-p2p-history"),
    path("school/p2p-alerts/<int:pk>/review", f.ReviewAlertView.as_view(), name="school-p2p-review"),
    path("school/privacy", f.PrivacyView.as_view(), name="school-privacy"),
    path("school/privacy/<int:pk>/handle", f.HandleRequestView.as_view(), name="school-privacy-handle"),
    path("school/tips", f.TipsView.as_view(), name="school-tips"),
    path("school/tips/new", f.SchoolTipFormView.as_view(), name="school-tip-new"),
    path("school/tips/<int:pk>/edit", f.SchoolTipFormView.as_view(), name="school-tip-edit"),
    path("school/tips/<int:pk>/delete", f.SchoolTipDeleteView.as_view(), name="school-tip-delete"),
    path("school/payment-issues", f.PaymentIssuesView.as_view(), name="school-payment-issues"),
]
