# Generated by Django 5.1.4 on 2026-09-20 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('branding', models.JSONField(blank=True, default=dict, help_text="e.g. {'logo_url': ..., 'primary_color': '#123456'}")),
                ('supported_languages', models.JSONField(blank=True, default=list, help_text="Subset of ['en', 'lg', 'sw'] this school offers to its users.")),
                ('policy_defaults', models.JSONField(blank=True, default=dict, help_text='Default spending caps / category restrictions / blocked items applied to new cards at this school. Enforcement is Part 2.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reward_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='tenants.school')),
                ('referring_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='tenants.school')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('referring_school', models.F('referred_school')), _negated=True), name='referral_cannot_self_reference')],
            },
        ),
    ]
