# Generated by Django 5.1.4 on 2026-09-30 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offline_spend_ceiling', models.DecimalField(decimal_places=2, default=2000, help_text='How far (UGX) a card may go below its cached balance across offline POS devices.', max_digits=12)),
                ('pin_lockout_threshold', models.PositiveSmallIntegerField(default=5, help_text='Wrong PINs reported within 24h that freeze a card.')),
                ('device_stale_after_hours', models.PositiveSmallIntegerField(default=24, help_text="A device that hasn't synced for this long is reported stale.")),
                ('attendance_notify_guardians', models.BooleanField(default=False, help_text="Notify guardians on a student's first tap-in of the day.")),
                ('attendance_on_canteen_devices', models.BooleanField(default=False, help_text='Allow canteen devices to record attendance taps too.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.school')),
            ],
            options={
                'verbose_name_plural': 'School settings',
            },
        ),
    ]
