"""
Builds locale/{lg,sw}/LC_MESSAGES/django.po and compiles django.mo from
notifications/translations.py -- in pure Python, because GNU gettext
(msgfmt / compilemessages) isn't available on every dev machine.
Re-run after changing any notification template, label or translation.
"""
import ast
import struct
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand
from django.utils import translation

from notifications import labels, templates, translations


def po_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def write_mo(path: Path, catalog: dict):
    """GNU .mo writer (little-endian, no hash table), as CPython's msgfmt.py."""
    keys = sorted(catalog)
    ids = strs = b""
    offsets = []
    for k in keys:
        kb, vb = k.encode(), catalog[k].encode()
        offsets.append((len(ids), len(kb), len(strs), len(vb)))
        ids += kb + b"\0"
        strs += vb + b"\0"
    n = len(keys)
    keystart = 7 * 4 + 16 * n
    valuestart = keystart + len(ids)
    koffsets, voffsets = [], []
    for o1, l1, o2, l2 in offsets:
        koffsets += [l1, o1 + keystart]
        voffsets += [l2, o2 + valuestart]
    output = struct.pack("Iiiiiii", 0x950412DE, 0, n, 7 * 4, 7 * 4 + n * 8, 0, 0)
    output += struct.pack(f"{len(koffsets)}i", *koffsets) + struct.pack(f"{len(voffsets)}i", *voffsets)
    path.write_bytes(output + ids + strs)


class Command(BaseCommand):
    help = "Generate lg/sw .po + .mo for notification templates and labels."

    def handle(self, *args, **options):
        header = ("Content-Type: text/plain; charset=UTF-8\n"
                  "Content-Transfer-Encoding: 8bit\n"
                  "Plural-Forms: nplurals=2; plural=(n != 1);\n")
        with translation.override(None):
            english_templates = {k: (str(t), str(b)) for k, (t, b) in templates.TEMPLATES.items()}
            english_labels = {k: str(v) for k, v in labels.LABELS.items()}
        base = Path(settings.LOCALE_PATHS[0])
        for lang in ("lg", "sw"):
            catalog = {"": header}
            missing = []
            for event, (title, body) in english_templates.items():
                tr = translations.TEMPLATES[lang].get(event)
                if not tr:
                    missing.append(event)
                    continue
                catalog[title], catalog[body] = tr
            for code, text in english_labels.items():
                if code in translations.LABELS[lang]:
                    catalog[text] = translations.LABELS[lang][code]
                else:
                    missing.append(f"label:{code}")
            out = base / lang / "LC_MESSAGES"
            out.mkdir(parents=True, exist_ok=True)
            lines = [f'# SchoolDimes notifications ({lang}). GENERATED by manage.py build_locale;',
                     "# edit notifications/translations.py instead.", 'msgid ""', f'msgstr "{po_escape(header)}"', ""]
            for msgid in sorted(k for k in catalog if k):
                lines += [f'msgid "{po_escape(msgid)}"', f'msgstr "{po_escape(catalog[msgid])}"', ""]
            (out / "django.po").write_text("\n".join(lines), encoding="utf-8")
            write_mo(out / "django.mo", catalog)
            self.stdout.write(self.style.SUCCESS(f"{lang}: {len(catalog) - 1} strings"))
            if missing:
                self.stdout.write(self.style.WARNING(f"{lang}: untranslated (falls back to English): {', '.join(missing)}"))
