# Generated by Django 5.1.4 on 2026-09-30 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0002_merchant_links'),
        ('students', '0001_initial'),
        ('tenants', '0002_schoolsettings'),
        ('wallets', '0006_merchant_settlement_wallets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_category', models.CharField(choices=[('wrong_amount', 'Charged the wrong amount'), ('not_received', 'Paid but item/service not received'), ('unauthorized', 'Not made by my child'), ('duplicate', 'Charged twice'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under review'), ('resolved_refunded', 'Resolved — refunded'), ('resolved_denied', 'Resolved — not refunded')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='wallets.ledgerentry')),
                ('pos_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='pos.postransaction')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='students.student')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'under_review'])), fields=('pos_transaction',), name='one_open_dispute_per_pos_transaction'), models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'under_review'])), fields=('ledger_entry',), name='one_open_dispute_per_ledger_entry'), models.CheckConstraint(condition=models.Q(models.Q(('ledger_entry__isnull', True), ('pos_transaction__isnull', False)), models.Q(('ledger_entry__isnull', False), ('pos_transaction__isnull', True)), _connector='OR'), name='dispute_has_exactly_one_target')],
            },
        ),
    ]
