# Generated by Django 5.1.4 on 2026-09-30 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('policies', '0002_copy_school_policy_defaults'),
        ('students', '0001_initial'),
        ('tenants', '0002_schoolsettings'),
        ('wallets', '0005_p2ptransfer_idempotency_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('device_role', models.CharField(choices=[('canteen', 'Canteen'), ('merchant', 'Merchant'), ('attendance', 'Attendance')], max_length=12)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('token_prefix', models.CharField(help_text='First characters of the token, for identification only.', max_length=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='tenants.school')),
            ],
            options={
                'ordering': ['school', 'device_name'],
            },
        ),
        migrations.CreateModel(
            name='PinFailureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_attempts', models.PositiveSmallIntegerField(default=1)),
                ('device_local_timestamp', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_failures', to='cards.card')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_failures', to='pos.device')),
            ],
        ),
        migrations.CreateModel(
            name='PosTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_uid', models.CharField(help_text='As sent by the device (kept even if unknown).', max_length=64)),
                ('channel', models.CharField(choices=[('offline_sync', 'Offline, synced later'), ('online', 'Online')], default='offline_sync', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Sale total as rung up.', max_digits=12)),
                ('applied_amount', models.DecimalField(decimal_places=2, default=0, help_text='Actually debited.', max_digits=12)),
                ('shortfall_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recovered_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('device_local_timestamp', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('sync_status', models.CharField(choices=[('applied', 'Applied'), ('shortfall', 'Applied with shortfall'), ('rejected', 'Rejected')], max_length=10)),
                ('reject_reason', models.CharField(blank=True, max_length=64)),
                ('flags', models.JSONField(blank=True, default=list, help_text='Policy/card rule codes the sale broke.')),
                ('pin_verified', models.BooleanField(blank=True, null=True)),
                ('ledger_reference', models.CharField(blank=True, max_length=64)),
                ('review_status', models.CharField(choices=[('none', 'No review needed'), ('pending', 'Pending review'), ('recovery_pending', 'Recovering shortfall'), ('resolved', 'Resolved')], default='none', max_length=20)),
                ('resolution', models.CharField(blank=True, choices=[('accept', 'Accepted as is'), ('write_off', 'Written off'), ('recover_from_next_topup', 'Recover from next top-up'), ('charge_guardian', 'Charge the guardian')], max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_transactions', to='cards.card')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='pos.device')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(help_text="The card holder's school (the tenant the money belongs to).", on_delete=django.db.models.deletion.CASCADE, related_name='pos_transactions', to='tenants.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_transactions', to='students.student')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_transactions', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PosTransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='policies.productcategory')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='policies.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.postransaction')),
            ],
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['school', 'review_status'], name='pos_postran_school__8e7da8_idx'),
        ),
        migrations.AddConstraint(
            model_name='postransaction',
            constraint=models.UniqueConstraint(fields=('device', 'idempotency_key'), name='pos_txn_idempotent_per_device'),
        ),
    ]
