# Generated by Django 5.1.4 on 2026-09-30 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='merchant',
            field=models.ForeignKey(blank=True, help_text='Merchant devices only.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='merchants.merchant'),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='merchant',
            field=models.ForeignKey(blank=True, help_text='Set for sales made on a merchant device.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_transactions', to='merchants.merchant'),
        ),
    ]
