# Generated by Django 5.1.4 on 2026-09-30 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('tenants', '0002_schoolsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('export', 'Export my data'), ('correction', 'Correct my data'), ('deletion', 'Delete my data')], max_length=12)),
                ('subject', models.CharField(choices=[('self', 'Myself'), ('student', 'A child of mine')], max_length=8)),
                ('details', models.TextField(blank=True, help_text="What to export/correct/delete, in the requester's words.")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('notes', models.TextField(blank=True, help_text="Handler's notes back to the requester.")),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_requests', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, help_text="The school that handles it: the student's school, or (subject=self) the school of the requester's first linked student.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_requests', to='tenants.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_requests', to='students.student')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
