# Generated by Django 5.1.4 on 2026-09-30 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('tenants', '0001_initial'),
        ('wallets', '0003_legacy_counter_entries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PooledFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('purpose', models.TextField(blank=True)),
                ('group_label', models.CharField(blank=True, help_text="Class/group, e.g. 'P4 Blue'", max_length=100)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('disbursed', 'Disbursed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pooled_funds_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pooled_funds', to='tenants.school')),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pooled_fund', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PooledFundContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.contributor')),
                ('contributor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deposit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pooled_fund_contribution', to='payments.deposit')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='pooled_funds.pooledfund')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PooledFundDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('destination', models.CharField(choices=[('school_settlement', 'School settlement wallet'), ('external', 'External payout (mobile money)')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disbursed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='pooled_funds.pooledfund')),
                ('payout', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payments.payout')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
