// Vectors generated by the BACKEND's own code (docs/PART3_PLAN.md):
//   docker compose exec web python manage.py shell -c "from django.contrib.auth.hashers import make_password; ..."
// If these fail, the device would accept wrong PINs or refuse right ones.
import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:schooldimes_pos/core/security/pbkdf2.dart';

const vectors = [
  ('1234', r'pbkdf2_sha256$870000$Zp1sAltValue0001$QjRoWpfHmhZknMcby7lVqmy5XHN+EwrR+Avul8TiC08='),
  ('0000', r'pbkdf2_sha256$870000$anotherSalt22$v3ZEuaz2beQ85WKFAOgileZXxdiAxxxT5XeeCvPKcPI='),
  ('987654', r'pbkdf2_sha256$870000$xxxxxxxxxxxxxxxxxxxxxx$GNC0zfuTYVfxwzgt0lnA0Rvr31DWg7TEf6b2aKL5KME='),
  ('2468', r'pbkdf2_sha256$870000$SchoolDimesSalt$akl9721dtzzIyeZ4woHKsVI9lFaxyeWNWhZguNlNN6Q='),
  ('1234', r'pbkdf2_sha256$1000$fastSalt01$kXeR5v6Y5+R5TXHhzRZuiU6D4eOockTRyEx9hRka19U='),
  ('5555', r'pbkdf2_sha256$1$fastSalt02$Om2sCKSzRV2SoeYCm9/Hi5ScUZE0Nk93jBvSoqrheVA='),
  ('31415', r'pbkdf2_sha256$12345$fastSalt03$1uXmD8+tsNc7dXqSHRiFR9zmA5PhI+I5+IHXJlMLkbM='),
];

void main() {
  test('sha256 known answer', () {
    expect(base64.encode(sha256(utf8.encode('abc'))), 'ungWv48Bz+pBQUDeXa4iI7ADYaOWF3qctBD/YfIAFa0=');
  });

  for (final (pin, encoded) in vectors) {
    final iterations = int.parse(encoded.split(r'$')[1]);
    test('Django vector $iterations iterations, PIN length ${pin.length}', () {
      expect(verifyDjangoPbkdf2(pin, encoded), isTrue);
      if (iterations < 100000) {
        // wrong PINs on the fast vectors (each 870k derivation takes ~1 s in debug)
        expect(verifyDjangoPbkdf2('${pin}9', encoded), isFalse);
        expect(verifyDjangoPbkdf2(pin == '0000' ? '0001' : '0000', encoded), isFalse);
      }
    }, timeout: const Timeout(Duration(minutes: 2)));
  }

  test('other schemes and malformed hashes are never accepted', () {
    expect(verifyDjangoPbkdf2('1234', r'argon2$argon2id$v=19$...'), isFalse);
    expect(verifyDjangoPbkdf2('1234', r'pbkdf2_sha256$x$salt$hash'), isFalse);
    expect(verifyDjangoPbkdf2('1234', ''), isFalse);
  });
}
