# Generated by Django 5.1.4 on 2026-09-30 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('pos', '0001_initial'),
        ('students', '0001_initial'),
        ('tenants', '0002_schoolsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=3)),
                ('device_local_timestamp', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cards.card')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='pos.device')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'ordering': ['-device_local_timestamp', '-id'],
                'indexes': [models.Index(fields=['school', 'device_local_timestamp'], name='attendance__school__ec3404_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'idempotency_key'), name='attendance_idempotent_per_device')],
            },
        ),
    ]
