# Generated by Django 5.1.4 on 2026-09-30 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relationship_label', models.CharField(blank=True, help_text="e.g. 'Grandmother'", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnmatchedWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('aggregator_ref', models.CharField(blank=True, max_length=64)),
                ('reason', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('reviewed', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('wallet_topup', 'Wallet top-up'), ('gift_voucher', 'Gift voucher'), ('pooled_fund_contribution', 'Pooled fund contribution')], default='wallet_topup', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('channel', models.CharField(choices=[('momo', 'Mobile money'), ('bank', 'Bank transfer'), ('ussd', 'USSD')], max_length=10)),
                ('payer_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('reference', models.CharField(help_text='Ours; echoed back by the aggregator.', max_length=40, unique=True)),
                ('aggregator_ref', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('instructions', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('failure_reason', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='payments.contributor')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='tenants.school')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GiftVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('message', models.CharField(blank=True, max_length=280)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('redeemed', 'Redeemed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gift_voucher', to='payments.deposit')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
                ('sender_contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_vouchers', to='payments.contributor')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_vouchers_sent', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_vouchers', to='students.student')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_vouchers', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('savings_withdrawal', 'Savings withdrawal'), ('pooled_fund_disbursement', 'Pooled fund disbursement')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone_number', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('aggregator_ref', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('failure_reason', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='tenants.school')),
                ('source_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RecurringTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('channel', models.CharField(choices=[('momo', 'Mobile money'), ('bank', 'Bank transfer'), ('ussd', 'USSD')], default='momo', max_length=10)),
                ('payer_phone', models.CharField(max_length=20)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, help_text='0=Monday .. 6=Sunday (weekly)', null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='1..28 (monthly)', null=True)),
                ('next_run_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=20)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_topups', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_topups', to='students.student')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_topups', to='wallets.wallet')),
            ],
            options={
                'ordering': ['next_run_at'],
            },
        ),
        migrations.AddField(
            model_name='deposit',
            name='recurring_topup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='payments.recurringtopup'),
        ),
        migrations.CreateModel(
            name='StudentTopUpLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_links', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_links', to='students.student')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topup_links', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
