# Generated by Django 5.1.4 on 2026-09-30 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_unhealthy', models.BooleanField(default=False, help_text="Counts toward the 'unhealthy share of spend' nutrition flag in analytics.")),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='tenants.school')),
            ],
            options={
                'verbose_name_plural': 'Product categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenants.school')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='policies.productcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_spend_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('weekly_spend_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('per_transaction_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('p2p_daily_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('p2p_enabled', models.BooleanField(blank=True, help_text='Null = inherit (school default null = enabled).', null=True)),
                ('low_balance_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='tenants.school')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_override', to='students.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('blocked_items', models.ManyToManyField(blank=True, related_name='+', to='policies.product')),
                ('allowed_categories', models.ManyToManyField(blank=True, help_text='Empty = every category allowed.', related_name='+', to='policies.productcategory')),
                ('blocked_categories', models.ManyToManyField(blank=True, related_name='+', to='policies.productcategory')),
            ],
            options={
                'verbose_name_plural': 'Policies',
                'ordering': ['school', 'student', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_category_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', True)), fields=('school',), name='one_default_policy_per_school'),
        ),
    ]
