# Generated by Django 5.1.4 on 2026-09-30 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('policies', '0002_copy_school_policy_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='allowed_merchants',
            field=models.ManyToManyField(blank=True, help_text='Empty = every approved merchant allowed.', related_name='+', to='merchants.merchant'),
        ),
        migrations.AddField(
            model_name='policy',
            name='blocked_merchants',
            field=models.ManyToManyField(blank=True, related_name='+', to='merchants.merchant'),
        ),
        migrations.AddField(
            model_name='product',
            name='merchant',
            field=models.ForeignKey(blank=True, help_text='Null = sold by the school canteen (Section G).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='merchants.merchant'),
        ),
    ]
