# Generated by Django 5.1.4 on 2026-09-20 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_uid', models.CharField(max_length=64, unique=True)),
                ('pin_hash', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('lost', 'Lost')], default='active', max_length=10)),
                ('biometric_enrolled', models.BooleanField(default=False, help_text='Flag only; biometric capture/matching is a client (Part 3/4) concern.')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='students.student')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
