# Generated by Django 5.1.4 on 2026-09-20 11:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(choices=[('main', 'Main'), ('savings', 'Savings')], max_length=10)),
                ('cached_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='students.student')),
            ],
            options={
                'ordering': ['student', 'wallet_type'],
                'unique_together': {('student', 'wallet_type')},
            },
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=255)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(limit_choices_to={'wallet_type': 'savings'}, on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to='wallets.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('entry_type', models.CharField(choices=[('deposit', 'Deposit'), ('pos_purchase', 'POS Purchase'), ('p2p_transfer_out', 'P2P Transfer Out'), ('p2p_transfer_in', 'P2P Transfer In'), ('savings_move_in', 'Savings Move In'), ('savings_move_out', 'Savings Move Out'), ('savings_withdrawal', 'Savings Withdrawal'), ('refund', 'Refund'), ('fee_payment', 'Fee Payment'), ('gift_voucher', 'Gift Voucher'), ('pooled_fund_contribution', 'Pooled Fund Contribution'), ('pooled_fund_disbursement', 'Pooled Fund Disbursement')], max_length=32)),
                ('reference_id', models.CharField(blank=True, help_text='Id of the source object (POS sale, transfer, etc.)', max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='tenants.school')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='wallets.wallet')),
            ],
            options={
                'verbose_name_plural': 'Ledger entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
