# Generated by Django 5.1.4 on 2026-09-30 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('pos_purchase', 'POS Purchase'), ('p2p_transfer_out', 'P2P Transfer Out'), ('p2p_transfer_in', 'P2P Transfer In'), ('savings_move_in', 'Savings Move In'), ('savings_move_out', 'Savings Move Out'), ('savings_withdrawal', 'Savings Withdrawal'), ('refund', 'Refund'), ('fee_payment', 'Fee Payment'), ('gift_voucher', 'Gift Voucher'), ('pooled_fund_contribution', 'Pooled Fund Contribution'), ('pooled_fund_disbursement', 'Pooled Fund Disbursement'), ('reversal', 'Reversal'), ('shortfall_recovery', 'Shortfall Recovery')], max_length=32),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Set for main/savings wallets; null for system wallets.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='students.student'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('main', 'Main'), ('savings', 'Savings'), ('school_settlement', 'School settlement'), ('aggregator_clearing', 'Aggregator clearing'), ('pooled_fund', 'Pooled fund'), ('merchant_settlement', 'Merchant settlement')], max_length=24),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('student__isnull', False), ('wallet_type__in', ['main', 'savings'])), models.Q(models.Q(('wallet_type__in', ['main', 'savings']), _negated=True), ('student__isnull', True)), _connector='OR'), name='wallet_student_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(condition=models.Q(('wallet_type__in', ['school_settlement', 'aggregator_clearing'])), fields=('school', 'wallet_type'), name='one_school_system_wallet_per_type'),
        ),
    ]
