# Generated by Django 5.1.4 on 2026-09-30 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
        ('wallets', '0003_legacy_counter_entries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='reached_at',
            field=models.DateTimeField(blank=True, help_text='Set once, when savings first reach target_amount (Part 2).', null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='withdrawal_window_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='withdrawal_window_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='P2PAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(choices=[('many_distinct_senders', 'Many distinct senders'), ('repeated_near_cap', 'Repeatedly sending near the cap')], max_length=32)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], default='open', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2p_alerts', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2p_alerts', to='students.student')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='P2PTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=140)),
                ('device_id_ref', models.BigIntegerField(blank=True, help_text='pos.Device id when initiated at a POS device with card + PIN.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiated_by', models.ForeignKey(blank=True, help_text='Guardian who initiated it (null when initiated at a POS device).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='p2p_received', to='wallets.wallet')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2p_transfers', to='tenants.school')),
                ('sender_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='p2p_sent', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
