# Generated by Django 5.1.4 on 2026-09-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_savings_window_goal_reached_p2p'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2ptransfer',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Set by POS-initiated transfers (retries).', max_length=128, null=True, unique=True),
        ),
    ]
