# Generated by Django 5.1.4 on 2026-09-30 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('students', '0001_initial'),
        ('tenants', '0002_schoolsettings'),
        ('wallets', '0005_p2ptransfer_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='merchant',
            field=models.ForeignKey(blank=True, help_text='Set only for merchant_settlement wallets (one per merchant per school).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_wallets', to='merchants.merchant'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(condition=models.Q(('wallet_type', 'merchant_settlement')), fields=('school', 'merchant'), name='one_merchant_settlement_wallet_per_school'),
        ),
    ]
